### ISSUE TITLE
Conversion doesn’t work in Firefox

### ISSUE THREAD

**Issue by raphaelbastide** [jimmywarting/ofc#15]
Hello, I tried to make it works locally. I should have missed the documentation, the README is empty and I don’t know how to make the converter work. It is seams stuck at conversion (no progress bar) and I don’t see any error or feedback. What did I miss?

**Comment by jimmywarting** [comment]
I just downloaded the master branch on my phone and it works fine in chrome.

Tried it on Firefox and it didn't work, but it works online. I'm sure it has to do with a more strict cross origin postMessage security. The docs says it has to match the protocol as well.

**Comment by raphaelbastide** [comment]
Confirmed, it is stuck in Firefox only.

**Comment by jimmywarting** [comment]
Do you have any idea how to tackle this issue. Or should I/we ignore it?

Write it in some readme?
