### ISSUE TITLE
License

### ISSUE THREAD

**Issue by raphaelbastide** [jimmywarting/ofc#17]
What is the license of this project?

**Comment by jimmywarting** [comment]
There is no licens...

**Comment by raphaelbastide** [comment]
The website http://onlinefontconverter.com/ mentions of Open Source. I don’t think the project can be open source if no open source license is attached to the source and if there is no documentation.
This project is really interesting and I can be happy to contribute / donate but it lacks basic instruction:
- What can I, can’t I do with the code (license). Contributors will not contribute if they are not sure of the license.
- How can I use the project (basic documentation for users)
- Context, credit, link to a demo or the website
I am a bit surprised of your answer seeing your GitHub activity. I think licenses and documentation are an important condition to open source software, as you can see on every projects on GitHub and others repository hosting service.

**Comment by jimmywarting** [comment]
What license would you recommend?

**Comment by raphaelbastide** [comment]
I don’t know, it depends on what you want user or developers to do. https://tldrlegal.com/
If you don’t chose an open source license, you’ll probably need to remove the mention «open source» on the website, and remove this repo from GitHub or make it private, as GitHub restricts the public repos to open source licenses.

**Comment by jimmywarting** [comment]
My head hurts from all the choices. I was thinking of MIT license cuz it's short and to the point. Developers are free to do whatever they want.

But then I thought about one part of my code that I don't want other to use... That is the private api key to mashape. It's not such a big of a deal if it publicly visible for people to steal it or just test it. But I would like them to get there own API key.

**Comment by raphaelbastide** [comment]
Maybe you can use .gitignore https://help.github.com/articles/ignoring-files/ and make a config-exemple file.

**Comment by jimmywarting** [comment]
Added MIT licens
