### ISSUE TITLE
Complete code

### ISSUE THREAD

**Issue by raphaelbastide** [jimmywarting/ofc#18]
While browsing the code, I found that the script is dependant from another one on your server:

		// start upload
		xhr.open("POST", "https://ofc.p.mashape.com/directConvert");
		xhr.setRequestHeader("X-Mashape-Key", "dFYPWXxpp3mshKD6Kimb4pVfvYLvp1YWcWfjsnErOY3HN8zs4a");
		xhr.responseType = "arraybuffer";
		xhr.send(fd);

If I get it right, this repository only concerns the web interface of http://onlinefontconverter.com/. Can you confirm?

**Comment by jimmywarting** [comment]
Comfirmed.
This Repo is just pure HTML/css/js making it possible to host all in github pages

**Comment by raphaelbastide** [comment]
Ok, it is more clear now. So what is open source exactly?
