### ISSUE TITLE
Issue converting font on Firefox

### ISSUE THREAD

**Issue by julesanchez** [jimmywarting/ofc#2]
I want to convert a .otf font to several others formats (svg, ttf, woff, eot). 
But on Firefox (v35.0.1 on Mac OS X),  I have the following Javascript error : 

`Error: The object could not be cloned.
n@https://afilepicker.github.io/u/js/min.js:1:14146
s/this.handler/<@https://afilepicker.github.io/u/js/min.js:1:6439
processQueue@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.js:12914:26
scheduleProcessQueue/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.js:12930:26
$RootScopeProvider/this.$get</Scope.prototype.$eval@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.js:14123:15
$RootScopeProvider/this.$get</Scope.prototype.$digest@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.js:13939:14
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.js:14227:12
Z</</<@https://afilepicker.github.io/u/js/min.js:1:14699
createEventHandler/eventHandler@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.js:3013:8`

Doing the same on Chrome works well.

**Comment by jimmywarting** [comment]
Think it's becose Firefox doesn't allow copy blobs cross domains/iframes
