### ISSUE TITLE
Cannot convert font due to the API issue

### ISSUE THREAD

**Issue by ytxmobile98** [jimmywarting/ofc#24]
Recently I tried to use this tool to convert PFB to TTF. There always appears a message that the Mashape is unable to respond.

**Comment by jimmywarting** [comment]
It works to communicate with Mashape now

**Comment by MHanslo** [comment]
Looks like it's down again; Missing Mashape application key.

**Comment by jimmywarting** [comment]
is it working for you now?

**Comment by MHanslo** [comment]
Confirmed, up and working again :+1:
