### ISSUE TITLE
Who made the API?

### ISSUE THREAD

**Issue by dovy** [jimmywarting/ofc#26]
I'd like to speak with them directly. ;)

**Comment by jimmywarting** [comment]
I'm

**Comment by dovy** [comment]
@jimmywarting Nice to meet you. Can we email? dxxxx@xxxux.xx or Skype: xxxxxxx?

**Comment by dovy** [comment]
Long story short, I keep bringing your service down and I'm building a small product off your API. I was wondering if you would let me make a mirror server with your help?
