### ISSUE TITLE
The website isn't working at all

### ISSUE THREAD

**Issue by Hanif1601** [jimmywarting/ofc#45]
When I visit this tool on my PC, this website is pretty useless currently and here what's looks like:

![inkedscreenshot_2018-12-20 online font converter_li](https://user-images.githubusercontent.com/46013833/50262091-fae1d400-0441-11e9-8804-4552ba7a41d2.jpg)

And here for technical info (see the highlight):

![image](https://user-images.githubusercontent.com/46013833/50262182-70e63b00-0442-11e9-8155-c513dc3a1212.png)

So, my known issue is the Mashape API may huge big update and no longer working on your website. That's why the checkbox thing doesn't appear. Hopefully you updating the Mashape API immediately!

**Comment by jimmywarting** [comment]
Works now

**Comment by Hanif1601** [comment]
Thanks for fixing your Mashape API! Now the website is working properly!
