### ISSUE TITLE
donated and didn't get my fonts! :(

### ISSUE THREAD

**Issue by aworkofmarc** [jimmywarting/ofc#47]
Uploaded fine. Seemed to convert fine. Downloaded? WHERE? Nope. Sent a donation but now got no fonts!

**Comment by jimmywarting** [comment]
Hi, sorry you didn't get the font.

donation is optional. And I can give you your money back. 

Would you like to send me the font and format you tried to convert to? so I can see what's wrong with the conversion. 
My email is jimmy@warting.se

**Comment by aworkofmarc** [comment]
Sent! TY Jimmy!

**Comment by KleinDevDE** [comment]
![image](https://user-images.githubusercontent.com/13904220/135448389-81a5a921-a2b4-4e2a-bcc8-1b80855f6b76.png)
Maybe u clicked on DONATE instead of "SAVE YOUR FONTS" ?
