### ISSUE TITLE
Failed to сonvert font

### ISSUE THREAD

**Issue by giv13** [jimmywarting/ofc#49]
OFC stopped converting fonts? I try to convert OpenSans, ProximaNova, SFProDisplay, Gilroy, etc. And always the result is "Failed to сonvert font". In the error log file is always the same: Unable to read the response.
PS. I choose formats:  woff,  woff2. And upload formats: ttf or otf. Windows 10, Google Chrome v76.0.3809.100

**Comment by jimmywarting** [comment]
Will look into it later when i'm available
could you share the file that you are trying to convert also?

**Comment by giv13** [comment]
Sent to jimmy@warting.se. Thanks!

**Comment by RuthlessRuler** [comment]
Can you please fix this problem?

**Comment by bradhogan** [comment]
Noticing this issue as well.  Any updates on this?  I've tried numerous font files and they all seem to fail - even files downloaded directly from the Google Fonts directory.  Cheers,

**Comment by jimmywarting** [comment]
Dose it work for you guys now?
updated some libs

**Comment by giv13** [comment]
Yes, works great! Big thanks!)
