### ISSUE TITLE
"Select Font" screen is in Swedish

### ISSUE THREAD

**Issue by thislooksfun** [jimmywarting/ofc#9]
Hello! I don't know if it's intentional or not (I'm guessing it isn't as the rest of the page is in English), but when I click "Select Font(s)," the popup is in Swedish.
![screen shot 2015-03-15 at 12 31 23 pm](https://cloud.githubusercontent.com/assets/5367333/6657111/42b5c626-cb0f-11e4-9e77-6d63b9635e9c.png)

**Comment by jimmywarting** [comment]
Fixed.

The popup is localized but i had a problem with the object reference. i should have copied it instead of changing the object

**Comment by thislooksfun** [comment]
Thanks! Awesome site btw.
